jobs:
  verify:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Download Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./test/ci

name: Workflow

on:
  schedule:
    - cron: "40 0/3 * * *"
